In [20]:
import torch
from torch.nn.utils.rnn import pad_sequence

ls = torch.nn.LogSoftmax(dim=-1)
t = torch.rand(10, 6, 3)
p = ls(t)

In [ ]:
torch.sum(p, dim)

tensor([[-3.3058, -3.2960, -3.3118, -3.2967, -3.3422, -3.3965],
        [-3.4560, -3.4571, -3.3333, -3.4888, -3.3595, -3.3499],
        [-3.4017, -3.2959, -3.3555, -3.3273, -3.2991, -3.3102],
        [-3.3510, -3.3723, -3.3306, -3.3341, -3.2988, -3.3078],
        [-3.3939, -3.3830, -3.3065, -3.3035, -3.3403, -3.3916],
        [-3.3051, -3.4689, -3.3552, -3.5426, -3.3468, -3.3508],
        [-3.3125, -3.4279, -3.4049, -3.3197, -3.3178, -3.4192],
        [-3.3906, -3.3048, -3.3244, -3.3604, -3.3320, -3.3199],
        [-3.5161, -3.2964, -3.4348, -3.4771, -3.4235, -3.3115],
        [-3.5106, -3.5345, -3.3774, -3.4859, -3.4673, -3.3068]])

In [24]:
ls = torch.nn.LogSoftmax()
t = torch.tensor([1.0, 2.0, 3.0])
ls(t), torch.sum(ls(t))

c:\Users\art3m\anaconda3\envs\dla\Lib\site-packages\torch\nn\modules\module.py:1773: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


(tensor([-2.4076, -1.4076, -0.4076]), tensor(-4.2228))

In [12]:
t = [
    torch.tensor([[1, 2, 3]]), 
    torch.tensor([[1, 2]]), 
    torch.tensor([[1, 2, 3, 4, 5]])
]
print(t[0].shape)
print(t[1].shape)
print(t[2].shape)
pad_sequence([a.squeeze() for a in t], batch_first=True)

torch.Size([1, 3])
torch.Size([1, 2])
torch.Size([1, 5])


tensor([[1, 2, 3, 0, 0],
        [1, 2, 0, 0, 0],
        [1, 2, 3, 4, 5]])